Added check if can create a file in reverse.

diff --git a/reverse b/reverse
--- a/reverse
+++ b/reverse
@@ -12,7 +12,11 @@ exit -8
 fi
 if ! [[ -f $2 ]]
 then 
-touch $2
+if ! [[ -w $2 ]]
+then
+echo "Can't create the file."
+exit -4
+fi
 fi
 if ! [[ -w $2 ]]
 then
